### PR TITLE
refers

### PR DESCRIPTION
**Pull request by arily**

### CODE REVIEW

**Comment by arily** [comment]
refers

**Comment by arily** [comment]
sorry, pr to wrong repo...

**Comment by cmyui** [comment]
Hey! @arily thank you for the solid submissions! I'll implement them on the real server.

Do you have any discord, email, or other way of contact? If you were interesting in contributing, I'd be fine with adding you to the contributors on git!

**Comment by arily** [comment]
Hi!
I got no python test environments so my code was not tested. Nokou’s fork should work!
By using fokanbtCommands.getMatchIDFromChannel(channel) we could get the MatchID!

It will be great if we could contributing to this project!

I got discord also emails.
Discord: arily#8735
Emai: a@ri.mk

**Pull request closed without merging**
